# Generated by Django 3.2.25 on 2025-02-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timer',
            name='duration',
            field=models.BigIntegerField(blank=True, default=True),
        ),
    ]
